"""Fix wrong back_populates

Revision ID: 283fc05d981d
Revises: fd58ac4f60fb
Create Date: 2025-04-21 11:45:53.159307

"""

from typing import Sequence, Union

from alembic import op
# Ensure all necessary types are imported here if needed globally

# revision identifiers, used by Alembic.
revision: str = "283fc05d981d"  # pragma: allowlist secret
down_revision: Union[str, None] = "fd58ac4f60fb"  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_foreign_key(
        None,
        "background_jobs",
        "videos",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "background_jobs", type_="foreignkey")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
